#pragma once

enum class PR4_LOAD_ERROR {
    OK,
    FILE_NOT_FOUND,
    INVALID_EXTENSION,
    CANT_OPEN,
    INVALID_MAGIC,
    INVALID_VERSION,
    SOMETHING_WRONG,
};

enum class PR4_WRITER_ERROR {
    OK,
    INVALID_EXTENSION,
    CANT_OPEN,
    SOMETHING_WRONG,
};
